<a href="https://colab.research.google.com/github/thafseera-salam/Flipkart-Smartphone-Market-Analysis-/blob/main/FLIPKART_MOBILE_python_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import glob

In [ ]:
#get all csv files
files= glob.glob("*.csv")
files

['flipkart 11.csv',
 'flipkart 38.csv',
 'flipkart 9.csv',
 'flipkart 21.csv',
 'flipkart 19.csv',
 'flipkart  24.csv',
 'flipkart 6.csv',
 'flipkart 7.csv',
 'flipkart 28.csv',
 'flipkart 25.csv',
 'flipkart 26.csv',
 '39.csv',
 'flipkart 31.csv',
 'flipkart 37.csv',
 'flipkart 16.csv',
 'flipkart 15.csv',
 'flipkart 36.csv',
 'flipkart 23.csv',
 'flipkart 40.csv',
 'FLIPKART 12.csv',
 'flipkart 10.csv',
 'flipkart 30.csv',
 'flipkart 17.csv',
 'flipkart 29.csv',
 'flipkart 27.csv',
 'flipkart18.csv',
 'flipkart 3.csv',
 'flipkart14.csv',
 'flipkart 8.csv',
 'flipkart 35.csv',
 'flipkart 33.csv',
 'flipkart 20.csv',
 'flipkart 5.csv',
 'flipkart 22.csv',
 'flipkart 1.csv',
 'flipkart 32.csv',
 'flipkart 4.csv',
 'flipkart 13.csv',
 'flipkart 2.csv',
 '34.csv']

In [ ]:
#combine them
df=pd.concat([pd.read_csv(file) for file in files],ignore_index=True)
df

,RG5Slk,MKiFS6,PvbNMB 2,DTBslk,DTBslk 2,DTBslk 3,DTBslk 4,DTBslk 5,DTBslk 6,hZ3P6w,kRYCnD,HQe8jr,qYp2rh src,HZ0E6r,HZ0E6r 2,HZ0E6r 3,HZ0E6r 4,fRrrYo,UCc1lI src 2,nvcpki
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219 Reviews,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,499","₹21,499",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹13,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330 Reviews,512 GB ROM,13.72 cm (5.4 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN,"₹94,900",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Bank Offer,"Or Pay ₹94,800 +",100,NaN,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32 Reviews,8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 8MP + 2MP | 20MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹23,859","₹30,999",23% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹18,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182 Reviews,12 GB RAM | 512 GB ROM,17.2 cm (6.77 inch) Display,50MP + 50MP | 50MP Front Camera,6000 mAh Battery,7 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹38,999","₹48,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,"Or Pay ₹8,999 +",30000,NaN,NaN,NaN,https://rukminim2.flixcart.com/www/100/100/pro...,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,850",Off on Exchange,Bank Offer,NaN,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86 Reviews,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,999",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5 Reviews,12 GB RAM | 256 GB ROM,16.91 cm (6.657 inch) Quad HD+ Display,200MP + 12MP | 12MP Front Camera,3900 mAh Battery,Qualcomm Snapdragon 8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹89,999","₹1,09,999",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print('total rows:',len(df))
df.head()

total rows: 1001

,RG5Slk,MKiFS6,PvbNMB 2,DTBslk,DTBslk 2,DTBslk 3,DTBslk 4,DTBslk 5,DTBslk 6,hZ3P6w,kRYCnD,HQe8jr,qYp2rh src,HZ0E6r,HZ0E6r 2,HZ0E6r 3,HZ0E6r 4,fRrrYo,UCc1lI src 2,nvcpki
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219 Reviews,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,499","₹21,499",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹13,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330 Reviews,512 GB ROM,13.72 cm (5.4 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN,"₹94,900",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Bank Offer,"Or Pay ₹94,800 +",100,NaN,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32 Reviews,8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 8MP + 2MP | 20MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹23,859","₹30,999",23% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹18,900",Off on Exchange,Bank Offer,NaN,NaN,NaN

In [ ]:
#saving combined files

df.to_csv("flipkart_mobile_data.csv",index=False)

In [ ]:
#removing duplicates

df.drop_duplicates()

,RG5Slk,MKiFS6,PvbNMB 2,DTBslk,DTBslk 2,DTBslk 3,DTBslk 4,DTBslk 5,DTBslk 6,hZ3P6w,kRYCnD,HQe8jr,qYp2rh src,HZ0E6r,HZ0E6r 2,HZ0E6r 3,HZ0E6r 4,fRrrYo,UCc1lI src 2,nvcpki
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219 Reviews,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,499","₹21,499",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹13,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330 Reviews,512 GB ROM,13.72 cm (5.4 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN,"₹94,900",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Bank Offer,"Or Pay ₹94,800 +",100,NaN,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32 Reviews,8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 8MP + 2MP | 20MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹23,859","₹30,999",23% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹18,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190 Reviews,8 GB RAM | 128 GB ROM,17.2 cm (6.77 inch) Display,50MP + 8MP | 50MP Front Camera,5600 mAh Battery,Dimensity 7300 Processor,1 Year Warranty on the Product and 6 Months Wa...,"₹26,990","₹33,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹21,450",Off on Exchange,Bank Offer,NaN,NaN,NaN
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182 Reviews,12 GB RAM | 512 GB ROM,17.2 cm (6.77 inch) Display,50MP + 50MP | 50MP Front Camera,6000 mAh Battery,7 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹38,999","₹48,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,"Or Pay ₹8,999 +",30000,NaN,NaN,NaN,https://rukminim2.flixcart.com/www/100/100/pro...,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,850",Off on Exchange,Bank Offer,NaN,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86 Reviews,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,999",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5 Reviews,12 GB RAM | 256 GB ROM,16.91 cm (6.657 inch) Quad HD+ Display,200MP + 12MP | 12MP Front Camera,3900 mAh Battery,Qualcomm Snapdragon 8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹89,999","₹1,09,999",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN

In [ ]:
print(df.columns)

Index(['RG5Slk', 'MKiFS6', 'PvbNMB 2', 'DTBslk', 'DTBslk 2', 'DTBslk 3',
       'DTBslk 4', 'DTBslk 5', 'DTBslk 6', 'hZ3P6w', 'kRYCnD', 'HQe8jr',
       'qYp2rh src', 'HZ0E6r', 'HZ0E6r 2', 'HZ0E6r 3', 'HZ0E6r 4', 'fRrrYo',
       'UCc1lI src 2', 'nvcpki'],
      dtype='object')

In [ ]:
#changing column name

df.columns=['Product Name','Rating','Reviews','GB|RAM','a','b','Battery_life','C','Warrenty','price','MRP','Discout','product link','D','Exchange_off','r','s','t','u','V']

df

,Product Name,Rating,Reviews,GB|RAM,a,b,Battery_life,C,Warrenty,price,MRP,Discout,product link,D,Exchange_off,r,s,t,u,V
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219 Reviews,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹17,499","₹21,499",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹13,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,"₹69,999","₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330 Reviews,512 GB ROM,13.72 cm (5.4 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN,"₹94,900",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Bank Offer,"Or Pay ₹94,800 +",100,NaN,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32 Reviews,8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 8MP + 2MP | 20MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,"₹23,859","₹30,999",23% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹18,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182 Reviews,12 GB RAM | 512 GB ROM,17.2 cm (6.77 inch) Display,50MP + 50MP | 50MP Front Camera,6000 mAh Battery,7 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹38,999","₹48,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,"Or Pay ₹8,999 +",30000,NaN,NaN,NaN,https://rukminim2.flixcart.com/www/100/100/pro...,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹13,999",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,850",Off on Exchange,Bank Offer,NaN,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86 Reviews,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹12,999",NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5 Reviews,12 GB RAM | 256 GB ROM,16.91 cm (6.657 inch) Quad HD+ Display,200MP + 12MP | 12MP Front Camera,3900 mAh Battery,Qualcomm Snapdragon 8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,"₹89,999","₹1,09,999",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

cleaning price and,MRP columns

In [ ]:
#coverting column to string first

df['price']=df['price'].astype(str)

In [ ]:
#apply cleaning

df['price']=df['price'].astype(str)
df['price']=df['price'].str.replace('₹','')
df['price']=df['price'].str.replace(',','')
df['price']=pd.to_numeric(df['price'], errors='coerce')

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,a,b,Battery_life,C,Warrenty,price,MRP,Discout,product link,D,Exchange_off,r,s,t,u,V
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219 Reviews,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,17499.0,"₹21,499",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹13,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,69999.0,"₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144 Reviews,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,69999.0,"₹87,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330 Reviews,512 GB ROM,13.72 cm (5.4 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN,94900.0,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Bank Offer,"Or Pay ₹94,800 +",100,NaN,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32 Reviews,8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 8MP + 2MP | 20MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,23859.0,"₹30,999",23% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹18,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182 Reviews,12 GB RAM | 512 GB ROM,17.2 cm (6.77 inch) Display,50MP + 50MP | 50MP Front Camera,6000 mAh Battery,7 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,38999.0,"₹48,999",20% off,https://static-assets-web.flixcart.com/fk-p-li...,"Or Pay ₹8,999 +",30000,NaN,NaN,NaN,https://rukminim2.flixcart.com/www/100/100/pro...,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86 Reviews,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,13999.0,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,850",Off on Exchange,Bank Offer,NaN,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86 Reviews,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,12999.0,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5 Reviews,12 GB RAM | 256 GB ROM,16.91 cm (6.657 inch) Quad HD+ Display,200MP + 12MP | 12MP Front Camera,3900 mAh Battery,Qualcomm Snapdragon 8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,89999.0,"₹1,09,999",18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
print(df['price'].dtype)

float64

In [ ]:
#MRP

df['MRP']=df['MRP'].astype(str)

In [ ]:
df['MRP']=df['MRP'].astype(str)
df['MRP']=df['MRP'].str.replace('₹','')
df['MRP']=df['MRP'].str.replace(',','')
df['MRP']=pd.to_numeric(df['MRP'], errors='coerce')
print(df['MRP'].dtype)

float64

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery_life,price,MRP,Discout
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,NaN
...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['Rating'].dtype

dtype('float64')

'reviews'

In [ ]:
df['Reviews']=pd.to_numeric(df['Reviews'].astype(str).str.replace('Reviews','').str.replace(',',''),errors='coerce')

In [ ]:
df['Reviews'].dtype

dtype('float64')

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,a,b,Battery_life,C,Warrenty,price,MRP,Discout,product link,D,Exchange_off,r,s,t,u,V
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,17.02 cm (6.7 inch) Full HD+ Display,50MP + 5MP + 2MP | 13MP Front Camera,5000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,17499.0,21499.0,18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹13,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,69999.0,87999.0,20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,16.94 cm (6.67 inch) Full HD+ AMOLED Display,50MP + 50MP + 50MP | 32MP Front Camera,6200 mAh Battery,Dimensity 9400+ Processor,1 Year Warranty on Handset and 6 Months Warran...,69999.0,87999.0,20% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,13.72 cm (5.4 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,A15 Bionic Chip Processor,1 year warranty for phone and 1 year warranty ...,NaN,94900.0,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Bank Offer,"Or Pay ₹94,800 +",100,NaN,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,16.94 cm (6.67 inch) Display,50MP + 8MP + 2MP | 20MP Front Camera,5500 mAh Battery,Dimensity 7300 Ultra Processor,1 Year Manufacturer Warranty for Phone and 6 M...,23859.0,30999.0,23% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹18,900",Off on Exchange,Bank Offer,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,17.2 cm (6.77 inch) Display,50MP + 50MP | 50MP Front Camera,6000 mAh Battery,7 Gen 3 Processor,1 Year Manufacturer Warranty for Device and 6 ...,38999.0,48999.0,20% off,https://static-assets-web.flixcart.com/fk-p-li...,"Or Pay ₹8,999 +",30000,NaN,NaN,NaN,https://rukminim2.flixcart.com/www/100/100/pro...,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,13999.0,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,850",Off on Exchange,Bank Offer,NaN,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,16.94 cm (6.67 inch) HD+ Display,32MP Rear Camera | 8MP Front Camera,6000 mAh Battery,Dimensity 6300 Processor,1 Year Manufacturer Warranty for Device and 6 ...,12999.0,NaN,NaN,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹10,000",Off on Exchange,Bank Offer,NaN,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,16.91 cm (6.657 inch) Quad HD+ Display,200MP + 12MP | 12MP Front Camera,3900 mAh Battery,Qualcomm Snapdragon 8 Elite for Galaxy Processor,1 Year Manufacturer Warranty for Device and 6 ...,89999.0,109999.0,18% off,https://static-assets-web.flixcart.com/fk-p-li...,Upto,"₹51,100",Off on Exchange,Bank Offer,NaN,NaN,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

or keep only wanted column

In [ ]:
df=df[['Product Name','Rating','Reviews','GB|RAM','Battery_life','price','MRP','Discout']]
df

,Product Name,Rating,Reviews,GB|RAM,Battery_life,price,MRP,Discout
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18% off
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20% off
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20% off
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23% off
...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20% off
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18% off
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.columns

Index(['Product Name', 'Rating', 'Reviews', 'GB|RAM', 'Battery_life', 'price',
       'MRP', 'Discout'],
      dtype='object')

removing '%' from discount column

In [ ]:
df['Discout']=pd.to_numeric(df['Discout'].astype(str).str.strip().str.replace('%','',regex=False).str.replace(',','',regex=False),errors='coerce')

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery_life,price,MRP,Discout
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,NaN
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,NaN
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,NaN
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,NaN
...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,NaN
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,NaN
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df['Discout'].unique()

array(['18% off', '20% off', nan, '23% off', '12% off', '5% off',
       '25% off', '11% off', '4% off', '16% off', '33% off', '6% off',
       '7% off', '31% off', '36% off', '30% off', '21% off', '22% off',
       '28% off', '8% off', '24% off', '19% off', '3% off', '17% off',
       '2% off', '15% off', '10% off', '9% off', '52% off', '13% off',
       '29% off', '27% off', '14% off', '26% off', '35% off', '32% off',
       '37% off', '42% off', '40% off', '38% off', '1% off', '47% off',
       '57% off', '44% off', '39% off', '34% off', '45% off', '55% off',
       '48% off', '41% off'], dtype=object)

In [ ]:
df_original = pd.read_csv("/content/flipkart_mobile_data.csv")

print(df_original.head())

                                          RG5Slk  MKiFS6     PvbNMB 2  \
0    Samsung Galaxy A16 5G (Light Green, 128 GB)     4.2  219 Reviews
1             vivo X200T (Seaside Lilac, 512 GB)     4.7  144 Reviews
2             vivo X200T (Stellar Black, 512 GB)     4.7  144 Reviews
3       Apple iPhone 13 mini (Starlight, 512 GB)     4.5  330 Reviews
4  REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)     4.3   32 Reviews

                   DTBslk                                      DTBslk 2  \
0   8 GB RAM | 128 GB ROM          17.02 cm (6.7 inch) Full HD+ Display
1  12 GB RAM | 512 GB ROM  16.94 cm (6.67 inch) Full HD+ AMOLED Display
2  12 GB RAM | 512 GB ROM  16.94 cm (6.67 inch) Full HD+ AMOLED Display
3              512 GB ROM  13.72 cm (5.4 inch) Super Retina XDR Display
4   8 GB RAM | 256 GB ROM                  16.94 cm (6.67 inch) Display

                                 DTBslk 3                   DTBslk 4  \
0    50MP + 5MP + 2MP | 13MP Front Camera           5000 mAh Battery
1  50MP + 50MP + 50MP | 32MP Front Camera           6200 mAh Battery
2  50MP + 50MP + 50MP | 32MP Front Camera           6200 mAh Battery
3         12MP + 12MP | 12MP Front Camera  A15 Bionic Chip Processor
4    50MP + 8MP + 2MP | 20MP Front Camera           5500 mAh Battery

                                            DTBslk 5  \
0                           Dimensity 6300 Processor
1                          Dimensity 9400+ Processor
2                          Dimensity 9400+ Processor
3  1 year warranty for phone and 1 year warranty ...
4                     Dimensity 7300 Ultra Processor

                                            DTBslk 6   hZ3P6w   kRYCnD  \
0  1 Year Manufacturer Warranty for Device and 6 ...  ₹17,499  ₹21,499
1  1 Year Warranty on Handset and 6 Months Warran...  ₹69,999  ₹87,999
2  1 Year Warranty on Handset and 6 Months Warran...  ₹69,999  ₹87,999
3                                                NaN  ₹94,900      NaN
4  1 Year Manufacturer Warranty for Phone and 6 M...  ₹23,859  ₹30,999

    HQe8jr                                         qYp2rh src      HZ0E6r  \
0  18% off  https://static-assets-web.flixcart.com/fk-p-li...        Upto
1  20% off  https://static-assets-web.flixcart.com/fk-p-li...        Upto
2  20% off  https://static-assets-web.flixcart.com/fk-p-li...        Upto
3      NaN  https://static-assets-web.flixcart.com/fk-p-li...  Bank Offer
4  23% off  https://static-assets-web.flixcart.com/fk-p-li...        Upto

           HZ0E6r 2         HZ0E6r 3    HZ0E6r 4 fRrrYo UCc1lI src 2 nvcpki
0           ₹13,900  Off on Exchange  Bank Offer    NaN          NaN    NaN
1           ₹51,100  Off on Exchange  Bank Offer    NaN          NaN    NaN
2           ₹51,100  Off on Exchange  Bank Offer    NaN          NaN    NaN
3  Or Pay ₹94,800 +              100         NaN    NaN          NaN    NaN
4           ₹18,900  Off on Exchange  Bank Offer    NaN          NaN    NaN

In [ ]:
df['Discout'] = df_original['HQe8jr']

In [ ]:
print(df_original['HQe8jr'].head(20))

0     18% off
1     20% off
2     20% off
3         NaN
4     23% off
5     12% off
6     23% off
7     12% off
8     18% off
9      5% off
10    25% off
11    25% off
12    25% off
13    12% off
14    11% off
15    11% off
16    11% off
17     4% off
18        NaN
19        NaN
Name: HQe8jr, dtype: object

In [ ]:
#adding these to new one

df['discount_original']=df_original['HQe8jr']

print(df[['Discout','discount_original']].head())

   Discout discount_original
0  18% off           18% off
1  20% off           20% off
2  20% off           20% off
3      NaN               NaN
4  23% off           23% off

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery_life,price,MRP,Discout,discount_original
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18% off,18% off
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20% off,20% off
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20% off,20% off
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23% off,23% off
...,...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20% off,20% off
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18% off,18% off
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df=df[['Product Name','Rating','Reviews','GB|RAM','Battery_life','price','MRP','Discout']]
df

,Product Name,Rating,Reviews,GB|RAM,Battery_life,price,MRP,Discout
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18% off
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20% off
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20% off
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23% off
...,...,...,...,...,...,...,...,...
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20% off
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18% off
1000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df.drop_duplicates(inplace=True)

/tmp/ipykernel_1263/3006716147.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop_duplicates(inplace=True)

In [ ]:
df['Discout']=df['Discout'].str.extract(r'(\d+)',expand=False)

/tmp/ipykernel_1263/3969513530.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Discout']=df['Discout'].str.extract(r'(\d+)',expand=False)

In [ ]:
df['Discout']=pd.to_numeric(df['Discout'],errors='coerce')

/tmp/ipykernel_1263/3196262005.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Discout']=pd.to_numeric(df['Discout'],errors='coerce')

In [ ]:
print(df['Discout'])

0       18.0
1       20.0
2       20.0
3        NaN
4       23.0
        ...
996     20.0
997      NaN
998      NaN
999     18.0
1000     NaN
Name: Discout, Length: 1001, dtype: float64

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery_life,price,MRP,Discout
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23.0
...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600 mAh Battery,26990.0,33999.0,20.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18.0

In [ ]:
df.rename(columns={'Discout':'Discount','Battery_life':'Battry_power'},inplace=True)
df

/tmp/ipykernel_1263/2956712659.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Discout':'Discount','Battery_life':'Battry_power'},inplace=True)

,Product Name,Rating,Reviews,GB|RAM,Battry_power1,price,MRP,Discount
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0
...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0

In [ ]:
df['Battry_power'].unique()

array(['5000 mAh Battery', '6200 mAh Battery',
       'A15 Bionic Chip Processor', '5500 mAh Battery',
       '7000 mAh Battery', '6000 mAh Battery', '4000 mAh Battery',
       'A18 Chip, 6 Core Processor Processor', nan,
       '4000 mAh Lithium ion Battery', '6500 mAh Li-ion battery Battery',
       '5000 mAh Lithium Battery',
       'Apple A10 Fusion 64-bit processor and Embedded M10 Motion Co-processor',
       '7025 mAh Battery', '6000 mAh Li-ion Battery',
       'A13 Bionic Chip Processor', '6580 mAh Battery',
       '4000 mAh Lithium-ion Battery', '7300 mAh Battery',
       '4400 mAh Battery', 'A19 Chip, 6 Core Processor Processor',
       '6500 mAh Battery', '3700 mAh Lithium Ion Battery',
       'A18 Pro Chip, 6 Core Processor Processor', '5020 mAh Battery',
       '1000 mAh Battery', '5160 mAh Battery', '5520 mAh Battery',
       '5000 mAh Lithium-ion Battery', '5000 mAh Lithium Ion Battery',
       '6040 mAh Battery', 'A15 Bionic Chip, 6 Core Processor Processor',
       '4015 mAh Lithium-ion Battery', '5700 mAh Battery',
       '5200 mAh Battery', '6300 mAh Battery', '4700 mAh Battery',
       '10001 mAh Battery', '5030 mAh Battery', '4900 mAh Battery',
       '1 year warranty for phone and 1 year warranty for in Box Accessories.',
       '5600 mAh Battery', '5000 mAh Li-ion Battery', '3000 mAh Battery',
       '4400 mAh Lithium ion Battery', '5030 mAh Lithium Polymer Battery',
       'A17 Pro Chip, 6 Core Processor Processor',
       '6000 mAh Lithium-ion Battery', '4300 mAh Li-ion Battery',
       '3700 mAh Battery', 'A18 Chip, 6 Core Processor',
       '4100 mAh Battery', '4035 mAh Battery', '5800 mAh Battery',
       'A9 Chip with 64-bit Architecture and M9 Motion Co-processor',
       '4300 mAh Battery', 'A16 Bionic Chip, 6 Core Processor Processor',
       '4900 mAh Li-ion Battery', '4830 mAh Lithium Battery',
       '4400 mAh Lithium Ion Battery',
       'A14 Bionic Chip with Next Generation Neural Engine Processor',
       'A10 Fusion Chip with 64-bit Architecture and Embedded M10 Motion Co-processor',
       '3700 mAh Lithium-ion Battery', '5110 mAh Battery',
       '7000 mAh Li-ion Battery', '5000 mAh Lithium Ion Polymer Battery',
       '5000 mAh Li-ion Battery Battery', '3300 mAh Lithium-ion Battery',
       '4500 mAh Battery', '6000 mAh Lithium Ion Battery',
       '3900 mAh Lithium Ion Battery', '4500 mAh Lithium-ion Battery',
       '6510 mAh Battery', '5080 mAh Battery',
       '5000 mAh Lithium Polymer Battery', '2000 mAh Battery',
       '5100 mAh Battery', '1500 mAh Battery', '3900 mAh Battery'],
      dtype=object)

In [ ]:
#finding products that doesnt have battery power

df[df['Battry_power'].str.contains('mAh' , na=False) ==False]

,Product Name,Rating,Reviews,GB|RAM,Battry_power,price,MRP,Discount
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
22,"Apple iPhone 16 (Ultramarine, 256 GB)",4.6,6925.0,256 GB ROM,"A18 Chip, 6 Core Processor Processor",74900.0,79900.0,6.0
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,"Apple iPhone 7 (Silver, 128 GB)",4.5,9100.0,128 GB ROM,Apple A10 Fusion 64-bit processor and Embedded...,34900.0,NaN,NaN
46,"Apple iPhone 11 Pro (Space Grey, 256 GB)",4.6,618.0,256 GB ROM,A13 Bionic Chip Processor,121300.0,NaN,NaN
...,...,...,...,...,...,...,...,...
961,"Apple iPhone 17e (Black, 256 GB)",4.8,0.0,256 GB ROM,1 year warranty for phone and 1 year warranty ...,64900.0,NaN,NaN
966,"Apple iPhone 17 Pro Max (Deep Blue, 256 GB)",4.8,39.0,256 GB ROM,"A19 Chip, 6 Core Processor Processor",149900.0,NaN,NaN
974,"Apple iPhone 17 Pro (Deep Blue, 1 TB)",4.7,72.0,1 TB ROM,"A19 Chip, 6 Core Processor Processor",174900.0,NaN,NaN
976,"Apple iPhone 17 Pro Max (Cosmic Orange, 2 TB)",4.8,39.0,2 TB ROM,"A19 Chip, 6 Core Processor Processor",229900.0,NaN,NaN
988,"Apple iPhone 17 Pro Max (Cosmic Orange, 256 GB)",4.8,39.0,256 GB ROM,"A19 Chip, 6 Core Processor Processor",149900.0,NaN,NaN

In [ ]:
df['battery_clean']=pd.to_numeric(df['Battry_power'].str.extract(r'(\d+)',expand=False),errors='coerce')
df

/tmp/ipykernel_1263/2076244686.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['battery_clean']=pd.to_numeric(df['Battry_power'].str.extract(r'(\d+)',expand=False),errors='coerce')

,Product Name,Rating,Reviews,GB|RAM,Battry_power,price,MRP,Discount,Battry_power1,battery_clean
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18.0,5000.0,5000.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0,6200.0,6200.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0,6200.0,6200.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN,15.0,15.0
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23.0,5500.0,5500.0
...,...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600 mAh Battery,26990.0,33999.0,20.0,5600.0,5600.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20.0,6000.0,6000.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN,6000.0,6000.0
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN,6000.0,6000.0
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18.0,3900.0,3900.0

In [ ]:
df=df[['Product Name','Rating','Reviews','GB|RAM','Battry_power1','price','MRP','Discount']]
df

,Product Name,Rating,Reviews,GB|RAM,Battry_power1,price,MRP,Discount
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,15.0,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0
...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0

In [ ]:
df['Battry_power1'] = df_original['DTBslk 4']

/tmp/ipykernel_1263/2306775857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Battry_power1'] = df_original['DTBslk 4']

In [ ]:
print(df_original['DTBslk 4'].head(20))

0              5000 mAh Battery
1              6200 mAh Battery
2              6200 mAh Battery
3     A15 Bionic Chip Processor
4              5500 mAh Battery
5              5500 mAh Battery
6              5000 mAh Battery
7              5500 mAh Battery
8              5000 mAh Battery
9              7000 mAh Battery
10             6200 mAh Battery
11             6000 mAh Battery
12             6000 mAh Battery
13             7000 mAh Battery
14             6000 mAh Battery
15             5500 mAh Battery
16             5500 mAh Battery
17             6000 mAh Battery
18             7000 mAh Battery
19             7000 mAh Battery
Name: DTBslk 4, dtype: object

In [ ]:

df['Battry_power1']=df_original['DTBslk 4']

/tmp/ipykernel_1263/2982580857.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Battry_power1']=df_original['DTBslk 4']

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battry_power1,price,MRP,Discount
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23.0
...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600 mAh Battery,26990.0,33999.0,20.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18.0

In [ ]:
df['battery_clean2']=df['Battry_power1'].str.extract(r'(\d+)\s*mAh',expand=False)
df['battery_clean2']=pd.to_numeric(df['battery_clean2'],errors='coerce')
df

/tmp/ipykernel_1263/1844007119.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['battery_clean2']=df['Battry_power1'].str.extract(r'(\d+)\s*mAh',expand=False)
/tmp/ipykernel_1263/1844007119.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['battery_clean2']=pd.to_numeric(df['battery_clean2'],errors='coerce')

,Product Name,Rating,Reviews,GB|RAM,Battry_power1,price,MRP,Discount,battery_clean2
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000 mAh Battery,17499.0,21499.0,18.0,5000.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0,6200.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200 mAh Battery,69999.0,87999.0,20.0,6200.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,A15 Bionic Chip Processor,94900.0,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500 mAh Battery,23859.0,30999.0,23.0,5500.0
...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600 mAh Battery,26990.0,33999.0,20.0,5600.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000 mAh Battery,38999.0,48999.0,20.0,6000.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,13999.0,NaN,NaN,6000.0
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000 mAh Battery,12999.0,NaN,NaN,6000.0
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900 mAh Battery,89999.0,109999.0,18.0,3900.0

In [ ]:
df['Battry_power1'] = df['battery_clean2']
df

/tmp/ipykernel_1263/3795901799.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Battry_power1'] = df['battery_clean2']

,Product Name,Rating,Reviews,GB|RAM,Battry_power1,price,MRP,Discount,battery_clean2
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0,5000.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,6200.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,6200.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0,5500.0
...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0,5600.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0,6000.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN,6000.0
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN,6000.0
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0,3900.0

In [ ]:
df=df[['Product Name','Rating','Reviews','GB|RAM','Battry_power1','price','MRP','Discount']]
df

,Product Name,Rating,Reviews,GB|RAM,Battry_power1,price,MRP,Discount
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0
...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0

In [ ]:
df.rename(columns={'Battry_power1':'Battery'},inplace=True)
df

/tmp/ipykernel_1263/1416754903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={'Battry_power1':'Battery'},inplace=True)

,Product Name,Rating,Reviews,GB|RAM,Battery,price,MRP,Discount
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0
...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0

In [ ]:
df['Brand']=df['Product Name'].str.split().str[0]
df['Brand']

0      Samsung
1         vivo
2         vivo
3        Apple
4        REDMI
        ...
995       vivo
996       vivo
997     realme
998     realme
999    Samsung
Name: Brand, Length: 833, dtype: object

In [ ]:
df['Model']=df['Product Name'].str.split().str[1:].str.join(' ')
df['Model']

0                 Galaxy A16 5G (Light Green, 128 GB)
1                       X200T (Seaside Lilac, 512 GB)
2                       X200T (Stellar Black, 512 GB)
3                  iPhone 13 mini (Starlight, 512 GB)
4             Note-14 Pro 5G (Phantom Purple, 256 GB)
                            ...
995                     V50e 5G (Pearl White, 128 GB)
996                         V50 5G (Rose Red, 512 GB)
997                       C73 5G (Jade Green, 128 GB)
998                        C73 5G (Onyx Black, 64 GB)
999    Galaxy S25 Edge 5G (Titanium Jetblack, 256 GB)
Name: Model, Length: 833, dtype: object

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery,price,MRP,Discount,Brand,Model
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0,Samsung,"Galaxy A16 5G (Light Green, 128 GB)"
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Seaside Lilac, 512 GB)"
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Stellar Black, 512 GB)"
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN,Apple,"iPhone 13 mini (Starlight, 512 GB)"
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0,REDMI,"Note-14 Pro 5G (Phantom Purple, 256 GB)"
...,...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0,vivo,"V50e 5G (Pearl White, 128 GB)"
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0,vivo,"V50 5G (Rose Red, 512 GB)"
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN,realme,"C73 5G (Jade Green, 128 GB)"
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN,realme,"C73 5G (Onyx Black, 64 GB)"
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0,Samsung,"Galaxy S25 Edge 5G (Titanium Jetblack, 256 GB)"

removing colour from product name

In [ ]:
import re

def remove_colour(name):
    return re.sub(r'\(.*?\)', '',str(name)).strip()

df['clean name'] = df['Product Name'].apply(remove_colour)
df['clean name']

0           Samsung Galaxy A16 5G
1                      vivo X200T
2                      vivo X200T
3            Apple iPhone 13 mini
4            REDMI Note-14 Pro 5G
                  ...
995                  vivo V50e 5G
996                   vivo V50 5G
997                 realme C73 5G
998                 realme C73 5G
999    Samsung Galaxy S25 Edge 5G
Name: clean name, Length: 833, dtype: object

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery,price,MRP,Discount,Brand,Model,clean name
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0,Samsung,"Galaxy A16 5G (Light Green, 128 GB)",Samsung Galaxy A16 5G
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Seaside Lilac, 512 GB)",vivo X200T
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Stellar Black, 512 GB)",vivo X200T
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN,Apple,"iPhone 13 mini (Starlight, 512 GB)",Apple iPhone 13 mini
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0,REDMI,"Note-14 Pro 5G (Phantom Purple, 256 GB)",REDMI Note-14 Pro 5G
...,...,...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0,vivo,"V50e 5G (Pearl White, 128 GB)",vivo V50e 5G
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0,vivo,"V50 5G (Rose Red, 512 GB)",vivo V50 5G
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN,realme,"C73 5G (Jade Green, 128 GB)",realme C73 5G
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN,realme,"C73 5G (Onyx Black, 64 GB)",realme C73 5G
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0,Samsung,"Galaxy S25 Edge 5G (Titanium Jetblack, 256 GB)",Samsung Galaxy S25 Edge 5G

In [ ]:
df['GB|RAM'].unique()

array(['8 GB RAM | 128 GB ROM', '12 GB RAM | 512 GB ROM', '512 GB ROM',
       '8 GB RAM | 256 GB ROM', '6 GB RAM | 128 GB ROM',
       '12 GB RAM | 256 GB ROM',
       '8 GB RAM | 128 GB ROM | Expandable Upto 2 TB', '256 GB ROM', nan,
       '6 GB RAM | 128 GB ROM | Expandable Upto 2 TB',
       '8 GB RAM | 256 GB ROM | Expandable Upto 2 TB',
       '4 GB RAM | 128 GB ROM',
       '6 GB RAM | 128 GB ROM | Expandable Upto 1 TB', '128 GB ROM',
       '3 GB RAM | 32 GB ROM',
       '8 GB RAM | 128 GB ROM | Expandable Upto 512 GB',
       '4 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
       '4 GB RAM | 128 GB ROM | Expandable Upto 2 TB',
       '4 GB RAM | 64 GB ROM',
       '4 GB RAM | 64 GB ROM | Expandable Upto 2 TB',
       '8 GB RAM | 256 GB ROM | Expandable Upto 1 TB',
       '4 GB RAM | 64 GB ROM | Expandable Upto 256 GB',
       '16 GB RAM | 512 GB ROM', '4 MB RAM | 128 GB ROM',
       '4 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
       '8 GB RAM | 128 GB ROM | Expandable Upto 128 GB',
       '4 GB RAM | 64.0 GB ROM | Expandable Upto 2 TB',
       '8 GB RAM | 128 GB ROM | Expandable Upto 256 GB',
       '3 GB RAM | 64 GB ROM | Expandable Upto 2 TB', '1 TB ROM',
       '8 GB RAM | 128 GB ROM | Expandable Upto 1 TB',
       '4 GB RAM | 64 GB ROM | Expandable Upto 400 GB',
       '8 MB RAM | 128 GB ROM | Expandable Upto 1 TB',
       '4 GB RAM | 64 GB ROM | Expandable Upto 512 GB',
       '8 GB RAM | 512 GB ROM',
       '4 GB RAM | 128.0 GB ROM | Expandable Upto 2 TB', '64 GB ROM',
       '4 GB RAM | 64 GB ROM | Expandable Upto 128 GB',
       '3 GB RAM | 64 GB ROM | Expandable Upto 1 TB',
       '12 GB RAM | 256 GB ROM | Expandable Upto 1 TB',
       '12 GB RAM | 1 TB ROM',
       '4 GB RAM | 128 GB ROM | Expandable Upto 256 GB',
       '2 GB RAM | 32 GB ROM',
       '6 GB RAM | 128.0 GB ROM | Expandable Upto 2 TB',
       '6 GB RAM | 128 GB ROM | Expandable Upto 256 GB',
       '3 GB RAM | 32 GB ROM | Expandable Upto 512 GB',
       '2 GB RAM | 32 GB ROM | Expandable Upto 512 GB',
       '4 GB RAM | 64 GB ROM | Expandable Upto 1500 GB',
       '1 GB RAM | 8 GB ROM',
       '6 GB RAM | 64 GB ROM | Expandable Upto 256 GB',
       '6 GB RAM | 128 GB ROM | Expandable Upto 1500 GB',
       '4 GB RAM | 128 GB ROM | Expandable Upto 1500 GB', '2 TB ROM'],
      dtype=object)

In [ ]:
df['RAM']= df['GB|RAM'].str.extract(r'(\d+)\s*GB\s*RAM',expand=False)
df['RAM']

0        8
1       12
2       12
3      NaN
4        8
      ...
995      8
996     12
997      4
998      4
999     12
Name: RAM, Length: 833, dtype: object

In [ ]:
df['Storage1']=df['GB|RAM'].str.extract(r'(\d+)\s*[gG][bB]\s*[rR][oO][mM]',expand=False)
df['Storage1']

0      128
1      512
2      512
3      512
4      256
      ...
995    128
996    512
997    128
998     64
999    256
Name: Storage1, Length: 833, dtype: object

In [ ]:
df

,Product Name,Rating,Reviews,GB|RAM,Battery,price,MRP,Discount,Brand,Model,clean name,RAM,Storage,Storage1
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0,Samsung,"Galaxy A16 5G (Light Green, 128 GB)",Samsung Galaxy A16 5G,8,128,128
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Seaside Lilac, 512 GB)",vivo X200T,12,512,512
2,"vivo X200T (Stellar Black, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Stellar Black, 512 GB)",vivo X200T,12,512,512
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN,Apple,"iPhone 13 mini (Starlight, 512 GB)",Apple iPhone 13 mini,NaN,512,512
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0,REDMI,"Note-14 Pro 5G (Phantom Purple, 256 GB)",REDMI Note-14 Pro 5G,8,256,256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,"vivo V50e 5G (Pearl White, 128 GB)",4.4,190.0,8 GB RAM | 128 GB ROM,5600.0,26990.0,33999.0,20.0,vivo,"V50e 5G (Pearl White, 128 GB)",vivo V50e 5G,8,128,128
996,"vivo V50 5G (Rose Red, 512 GB)",4.5,182.0,12 GB RAM | 512 GB ROM,6000.0,38999.0,48999.0,20.0,vivo,"V50 5G (Rose Red, 512 GB)",vivo V50 5G,12,512,512
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN,realme,"C73 5G (Jade Green, 128 GB)",realme C73 5G,4,128,128
998,"realme C73 5G (Onyx Black, 64 GB)",4.2,86.0,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,6000.0,12999.0,NaN,NaN,realme,"C73 5G (Onyx Black, 64 GB)",realme C73 5G,4,64,64
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0,Samsung,"Galaxy S25 Edge 5G (Titanium Jetblack, 256 GB)",Samsung Galaxy S25 Edge 5G,12,256,256

In [ ]:
df['Storage']=df['Storage1']

In [ ]:
df=df.drop_duplicates(subset=['Brand','clean name','Storage','RAM'])
df

,Product Name,Rating,Reviews,GB|RAM,Battery,price,MRP,Discount,Brand,Model,clean name,RAM,Storage,Storage1
0,"Samsung Galaxy A16 5G (Light Green, 128 GB)",4.2,219.0,8 GB RAM | 128 GB ROM,5000.0,17499.0,21499.0,18.0,Samsung,"Galaxy A16 5G (Light Green, 128 GB)",Samsung Galaxy A16 5G,8,128,128
1,"vivo X200T (Seaside Lilac, 512 GB)",4.7,144.0,12 GB RAM | 512 GB ROM,6200.0,69999.0,87999.0,20.0,vivo,"X200T (Seaside Lilac, 512 GB)",vivo X200T,12,512,512
3,"Apple iPhone 13 mini (Starlight, 512 GB)",4.5,330.0,512 GB ROM,NaN,94900.0,NaN,NaN,Apple,"iPhone 13 mini (Starlight, 512 GB)",Apple iPhone 13 mini,NaN,512,512
4,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)",4.3,32.0,8 GB RAM | 256 GB ROM,5500.0,23859.0,30999.0,23.0,REDMI,"Note-14 Pro 5G (Phantom Purple, 256 GB)",REDMI Note-14 Pro 5G,8,256,256
5,"vivo T4 Ultra 5G (Meteor Grey, 256 GB)",4.5,540.0,8 GB RAM | 256 GB ROM,5500.0,35999.0,40999.0,12.0,vivo,"T4 Ultra 5G (Meteor Grey, 256 GB)",vivo T4 Ultra 5G,8,256,256
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,"Samsung Galaxy S26 5G (Cobalt Violet, 256 GB)",4.7,2.0,12 GB RAM | 256 GB ROM,4300.0,87999.0,NaN,NaN,Samsung,"Galaxy S26 5G (Cobalt Violet, 256 GB)",Samsung Galaxy S26 5G,12,256,256
986,"Samsung Galaxy S23 Ultra 5G (Cream, 512 GB)",4.6,404.0,12 GB RAM | 512 GB ROM,5000.0,161999.0,NaN,NaN,Samsung,"Galaxy S23 Ultra 5G (Cream, 512 GB)",Samsung Galaxy S23 Ultra 5G,12,512,512
994,"Samsung Galaxy F34 5G (Mystic Green, 128 GB)",4.2,1205.0,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,6000.0,25999.0,NaN,NaN,Samsung,"Galaxy F34 5G (Mystic Green, 128 GB)",Samsung Galaxy F34 5G,8,128,128
997,"realme C73 5G (Jade Green, 128 GB)",4.2,86.0,4 GB RAM | 128 GB ROM | Expandable Upto 2 TB,6000.0,13999.0,NaN,NaN,realme,"C73 5G (Jade Green, 128 GB)",realme C73 5G,4,128,128
999,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...",4.7,5.0,12 GB RAM | 256 GB ROM,3900.0,89999.0,109999.0,18.0,Samsung,"Galaxy S25 Edge 5G (Titanium Jetblack, 256 GB)",Samsung Galaxy S25 Edge 5G,12,256,256

In [ ]:
df.columns

Index(['Product Name', 'Rating', 'Reviews', 'GB|RAM', 'Battery', 'price',
       'MRP', 'Discount', 'Brand', 'Model', 'clean name', 'RAM', 'Storage',
       'Storage1'],
      dtype='object')

In [ ]:
df=df[['Brand','clean name','RAM','Storage','Battery','price','MRP','Discount','Rating','Reviews','Product Name','Model','GB|RAM']]
df

,Brand,clean name,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Product Name,Model,GB|RAM
0,Samsung,Samsung Galaxy A16 5G,8,128,5000.0,17499.0,21499.0,18.0,4.2,219.0,"Samsung Galaxy A16 5G (Light Green, 128 GB)","Galaxy A16 5G (Light Green, 128 GB)",8 GB RAM | 128 GB ROM
1,vivo,vivo X200T,12,512,6200.0,69999.0,87999.0,20.0,4.7,144.0,"vivo X200T (Seaside Lilac, 512 GB)","X200T (Seaside Lilac, 512 GB)",12 GB RAM | 512 GB ROM
3,Apple,Apple iPhone 13 mini,NaN,512,NaN,94900.0,NaN,NaN,4.5,330.0,"Apple iPhone 13 mini (Starlight, 512 GB)","iPhone 13 mini (Starlight, 512 GB)",512 GB ROM
4,REDMI,REDMI Note-14 Pro 5G,8,256,5500.0,23859.0,30999.0,23.0,4.3,32.0,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)","Note-14 Pro 5G (Phantom Purple, 256 GB)",8 GB RAM | 256 GB ROM
5,vivo,vivo T4 Ultra 5G,8,256,5500.0,35999.0,40999.0,12.0,4.5,540.0,"vivo T4 Ultra 5G (Meteor Grey, 256 GB)","T4 Ultra 5G (Meteor Grey, 256 GB)",8 GB RAM | 256 GB ROM
...,...,...,...,...,...,...,...,...,...,...,...,...,...
983,Samsung,Samsung Galaxy S26 5G,12,256,4300.0,87999.0,NaN,NaN,4.7,2.0,"Samsung Galaxy S26 5G (Cobalt Violet, 256 GB)","Galaxy S26 5G (Cobalt Violet, 256 GB)",12 GB RAM | 256 GB ROM
986,Samsung,Samsung Galaxy S23 Ultra 5G,12,512,5000.0,161999.0,NaN,NaN,4.6,404.0,"Samsung Galaxy S23 Ultra 5G (Cream, 512 GB)","Galaxy S23 Ultra 5G (Cream, 512 GB)",12 GB RAM | 512 GB ROM
994,Samsung,Samsung Galaxy F34 5G,8,128,6000.0,25999.0,NaN,NaN,4.2,1205.0,"Samsung Galaxy F34 5G (Mystic Green, 128 GB)","Galaxy F34 5G (Mystic Green, 128 GB)",8 GB RAM | 128 GB ROM | Expandable Upto 1 TB
997,realme,realme C73 5G,4,128,6000.0,13999.0,NaN,NaN,4.2,86.0,"realme C73 5G (Jade Green, 128 GB)","C73 5G (Jade Green, 128 GB)",4 GB RAM | 128 GB ROM | Expandable Upto 2 TB
999,Samsung,Samsung Galaxy S25 Edge 5G,12,256,3900.0,89999.0,109999.0,18.0,4.7,5.0,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,...","Galaxy S25 Edge 5G (Titanium Jetblack, 256 GB)",12 GB RAM | 256 GB ROM

In [ ]:
df.to_csv('flipkart_Phone_market_analysis.csv',index=False )

In [ ]:
df = pd.read_csv('/content/smartphone_analysis.csv')
df

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name
0,Samsung,Galaxy A16 5G,8,128.0,5000,17499,21499,18,4.2,219.0,Midrange,919.8,0.052563,2187.375000,"Samsung Galaxy A16 5G (Light Green, 128 GB)"
1,vivo,X200T,12,512.0,6200,69999,87999,20,4.7,144.0,Premium,676.8,0.009669,5833.250000,"vivo X200T (Seaside Lilac, 512 GB)"
2,Apple,iPhone 13 mini,Not specified,512.0,Unknown,94900,Actual,No discount,4.5,330.0,Premium,1485.0,0.015648,0.000000,"Apple iPhone 13 mini (Starlight, 512 GB)"
3,REDMI,Note-14 Pro 5G,8,256.0,5500,23859,30999,23,4.3,32.0,Midrange,137.6,0.005767,2982.375000,"REDMI Note-14 Pro 5G (Phantom Purple, 256 GB)"
4,vivo,T4 Ultra 5G,8,256.0,5500,35999,40999,12,4.5,540.0,Midrange,2430.0,0.067502,4499.875000,"vivo T4 Ultra 5G (Meteor Grey, 256 GB)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
443,Samsung,Galaxy S26 5G,12,256.0,4300,87999,Actual,No discount,4.7,2.0,Premium,9.4,0.000107,7333.250000,"Samsung Galaxy S26 5G (Cobalt Violet, 256 GB)"
444,Samsung,Galaxy S23 Ultra 5G,12,512.0,5000,161999,Actual,No discount,4.6,404.0,Premium,1858.4,0.011472,13499.916667,"Samsung Galaxy S23 Ultra 5G (Cream, 512 GB)"
445,Samsung,Galaxy F34 5G,8,128.0,6000,25999,Actual,No discount,4.2,1205.0,Midrange,5061.0,0.194661,3249.875000,"Samsung Galaxy F34 5G (Mystic Green, 128 GB)"
446,realme,C73 5G,4,128.0,6000,13999,Actual,No discount,4.2,86.0,Budget,361.2,0.025802,3499.750000,"realme C73 5G (Jade Green, 128 GB)"
447,Samsung,Galaxy S25 Edge 5G,12,256.0,3900,89999,109999,18,4.7,5.0,Premium,23.5,0.000261,7499.916667,"Samsung Galaxy S25 Edge 5G (Titanium Jetblack,..."

In [ ]:
fill_rows = df[(df['Storage'] == 0) | (df['Storage'].isna())]
fill_rows

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name
106,vivo,Y19s 5G,4,0.0,6000,12499,14999,16,4.3,2.0,Budget,8.6,0.000688,3124.750000,"vivo Y19s 5G (Titanium Silver, 64.0 GB)"
119,Apple,iPhone 17 Pro,Not specified,NaN,Unknown,174900,Actual,No discount,4.7,72.0,Premium,338.4,0.001935,0.000000,"Apple iPhone 17 Pro (Silver, 1 TB)"
248,Samsung,Galaxy Z Fold6 5G,12,NaN,4400,185999,200999,7,4.2,16.0,Premium,67.2,0.000361,15499.916667,"Samsung Galaxy Z Fold6 5G (Silver Shadow, 1 TB)"
276,vivo,Y19s 5G,6,0.0,6000,15499,17499,11,4.5,3.0,Midrange,13.5,0.000871,2583.166667,"vivo Y19s 5G (Majestic Green, 128.0 GB)"
423,Apple,iPhone 17 Pro Max,Not specified,NaN,Unknown,189900,Actual,No discount,4.8,39.0,Premium,187.2,0.000986,0.000000,"Apple iPhone 17 Pro Max (Cosmic Orange, 1 TB)"

In [ ]:
df['Storage']=df['Storage'].replace(0, 1000)
df['Storage']

0      128.0
1      512.0
2      512.0
3      256.0
4      256.0
       ...
443    256.0
444    512.0
445    128.0
446    128.0
447    256.0
Name: Storage, Length: 448, dtype: float64

In [ ]:
fill_rows = df[(df['Storage'] == 0) | (df['Storage'].isna())]
fill_rows

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name
119,Apple,iPhone 17 Pro,Not specified,NaN,Unknown,174900,Actual,No discount,4.7,72.0,Premium,338.4,0.001935,0.000000,"Apple iPhone 17 Pro (Silver, 1 TB)"
248,Samsung,Galaxy Z Fold6 5G,12,NaN,4400,185999,200999,7,4.2,16.0,Premium,67.2,0.000361,15499.916667,"Samsung Galaxy Z Fold6 5G (Silver Shadow, 1 TB)"
423,Apple,iPhone 17 Pro Max,Not specified,NaN,Unknown,189900,Actual,No discount,4.8,39.0,Premium,187.2,0.000986,0.000000,"Apple iPhone 17 Pro Max (Cosmic Orange, 1 TB)"

In [ ]:
df['Storage']=df['Storage'].replace(1000, 0)
df['Storage']

0      128.0
1      512.0
2      512.0
3      256.0
4      256.0
       ...
443    256.0
444    512.0
445    128.0
446    128.0
447    256.0
Name: Storage, Length: 448, dtype: float64

In [ ]:
fill_rows = df[(df['Storage'] == 0) | (df['Storage'].isna())]
fill_rows

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name
106,vivo,Y19s 5G,4,0.0,6000,12499,14999,16,4.3,2.0,Budget,8.6,0.000688,3124.750000,"vivo Y19s 5G (Titanium Silver, 64.0 GB)"
119,Apple,iPhone 17 Pro,Not specified,NaN,Unknown,174900,Actual,No discount,4.7,72.0,Premium,338.4,0.001935,0.000000,"Apple iPhone 17 Pro (Silver, 1 TB)"
248,Samsung,Galaxy Z Fold6 5G,12,NaN,4400,185999,200999,7,4.2,16.0,Premium,67.2,0.000361,15499.916667,"Samsung Galaxy Z Fold6 5G (Silver Shadow, 1 TB)"
276,vivo,Y19s 5G,6,0.0,6000,15499,17499,11,4.5,3.0,Midrange,13.5,0.000871,2583.166667,"vivo Y19s 5G (Majestic Green, 128.0 GB)"
423,Apple,iPhone 17 Pro Max,Not specified,NaN,Unknown,189900,Actual,No discount,4.8,39.0,Premium,187.2,0.000986,0.000000,"Apple iPhone 17 Pro Max (Cosmic Orange, 1 TB)"

In [ ]:
df['Storage']=df['Storage'].fillna(1000)
df['Storage']

0      128.0
1      512.0
2      512.0
3      256.0
4      256.0
       ...
443    256.0
444    512.0
445    128.0
446    128.0
447    256.0
Name: Storage, Length: 448, dtype: float64

In [ ]:
fill_rows = df[(df['Storage'] == 0) | (df['Storage'].isna())]
fill_rows

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name
106,vivo,Y19s 5G,4,0.0,6000,12499,14999,16,4.3,2.0,Budget,8.6,0.000688,3124.750000,"vivo Y19s 5G (Titanium Silver, 64.0 GB)"
276,vivo,Y19s 5G,6,0.0,6000,15499,17499,11,4.5,3.0,Midrange,13.5,0.000871,2583.166667,"vivo Y19s 5G (Majestic Green, 128.0 GB)"

In [ ]:
df.loc[(df['RAM'] == 4) & (df['Storage'] == 0), 'Storage'] = 64

In [ ]:
df.loc[(df['RAM'] == 6) & (df['Storage'] == 0), 'Storage'] = 128

In [ ]:
fill_rows = df[(df['Storage'] == 0) | (df['Storage'].isna())]
fill_rows

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name
106,vivo,Y19s 5G,4,0.0,6000,12499,14999,16,4.3,2.0,Budget,8.6,0.000688,3124.750000,"vivo Y19s 5G (Titanium Silver, 64.0 GB)"
276,vivo,Y19s 5G,6,0.0,6000,15499,17499,11,4.5,3.0,Midrange,13.5,0.000871,2583.166667,"vivo Y19s 5G (Majestic Green, 128.0 GB)"

In [ ]:
# Convert storage to numeric just in case it's stored as text
df['Storage	'] = pd.to_numeric(df['Storage'], errors='coerce')

# Now try the update again
df.loc[(df['RAM'] == 4) & (df['Storage'] == 0), 'Storage'] = 64
df.loc[(df['RAM'] == 6) & (df['Storage'] == 0), 'Storage'] = 128

In [ ]:
# Run the update
df.loc[(df['RAM'] == 4) & (df['Storage'] == 0), 'Storage'] = 64

# Check the specific rows immediately
print(df[df['RAM'] == 4])

Empty DataFrame
Columns: [Brand, Model, RAM, Storage, Battery, price, MRP, Discount, Rating, Reviews, Price_Catogery, Popularity_score, Value_for_money_score, Price/GB RAM, Product Name, Storage	]
Index: []

In [ ]:
fill_rows = df[(df['Storage'] == 0) | (df['Storage'].isna())]
fill_rows

,Brand,Model,RAM,Storage,Battery,price,MRP,Discount,Rating,Reviews,Price_Catogery,Popularity_score,Value_for_money_score,Price/GB RAM,Product Name,Storage\t
106,vivo,Y19s 5G,4,0.0,6000,12499,14999,16,4.3,2.0,Budget,8.6,0.000688,3124.750000,"vivo Y19s 5G (Titanium Silver, 64.0 GB)",0.0
276,vivo,Y19s 5G,6,0.0,6000,15499,17499,11,4.5,3.0,Midrange,13.5,0.000871,2583.166667,"vivo Y19s 5G (Majestic Green, 128.0 GB)",0.0

In [ ]:
df['Storage']==0

0      False
1      False
2      False
3      False
4      False
       ...
443    False
444    False
445    False
446    False
447    False
Name: Storage, Length: 448, dtype: bool

In [ ]:
df.columns

Index(['Brand', 'Model', 'RAM', 'Storage', 'Battery', 'price', 'MRP',
       'Discount', 'Rating', 'Reviews', 'Price_Catogery', 'Popularity_score',
       'Value_for_money_score', 'Price/GB RAM', 'Product Name'],
      dtype='object')

In [ ]:
df = df.drop('Storage\t', axis=1)

In [ ]:
df.to_csv("Flipkart Smartphone Analysis.csv", index=False)